version: '3.1'
services:
  registry: 
    image: registry
    restart: always
    container_name: registry
    ports: 
      - 5000:5000
    volumes:
      - /usr/local/docker/registry/data:/var/lib/registry
      
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    container_name: docker-registry-frontend
    ports:
      - 80:80
    volumes:
      - ./certs/frontend.crt:/etc/apache2/server.crt:ro
      - ./certs/frontend.key:/etc/apache2/server.key:ro
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.43.241
      - ENV_DOCKER_REGISTRY_PORT=5000
